# payment_centralization_api/config/database.yml
default: &default
  adapter: postgresql
  encoding: unicode
  # For RSpec:
  # template: template0
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: payment_centralization_api_development
  host: db # O nome do serviço do banco de dados no docker-compose
  username: postgres
  password: password

test:
  <<: *default
  database: payment_centralization_api_test
  host: db
  username: postgres
  password: password

production:
  <<: *default
  database: payment_centralization_api_production
  username: <%= ENV['PAYMENT_CENTRALIZATION_API_DATABASE_USERNAME'] %>
  password: <%= ENV['PAYMENT_CENTRALIZATION_API_DATABASE_PASSWORD'] %>
  host: <%= ENV['PAYMENT_CENTRALIZATION_API_DATABASE_HOST'] %>